version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-2204:2024.11.1
    resource_class: large
    steps:
      - checkout
      - run: sudo apt-get update && sudo apt-get install -y xz-utils zipalign zip
      - run: export USER=$(whoami) && ARCHES="aarch64" ./scripts/android/build-android.sh -gs
