version: 2.1

jobs:
  build:
    docker:
      - image: cimg/android:2025.02
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            echo "Installing dependencies..."
            sudo apt-get update && sudo apt-get install -y xz-utils zipalign zip
      - run:
          name: Build the project
          command: |
            echo "Building the project..."
            export USER=$(whoami)
            ARCHES="aarch64" ./scripts/android/build-android.sh -gs

workflows:
  build_and_test:
    jobs:
      - build
